apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-dns-egress.yaml
  - allow-traefik-ingress.yaml
  - cert-manager-http01-solver-ingress.yaml
  - allow-prometheus-ingress.yaml
  - allow-postgres-egress.yaml
  - allow-redis-egress.yaml
  - allow-postgres-ingress.yaml
  - allow-redis-ingress.yaml
  - allow-backup-object-storage-egress.yaml
