apiVersion: v1
kind: Service
metadata:
  name: smartenergy-api
  labels:
    app.kubernetes.io/name: smartenergy
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: smartenergy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smartenergy
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
