"""baseline phase 2 schema

Revision ID: 56bac6c30106
Revises: 
Create Date: 2025-10-07 09:23:56.833408+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bac6c30106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_exported',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('measure_value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_exported_timestamp'), 'energy_exported', ['timestamp'], unique=False)
    op.create_table('energy_imported',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('measure_value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_imported_timestamp'), 'energy_imported', ['timestamp'], unique=False)
    op.create_table('energy_reactive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('imported_kvarh', sa.Float(), nullable=False),
    sa.Column('exported_kvarh', sa.Float(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_reactive_timestamp'), 'energy_reactive', ['timestamp'], unique=False)
    op.create_table('max_power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('measure_value', sa.Float(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_max_power_timestamp'), 'max_power', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_max_power_timestamp'), table_name='max_power')
    op.drop_table('max_power')
    op.drop_index(op.f('ix_energy_reactive_timestamp'), table_name='energy_reactive')
    op.drop_table('energy_reactive')
    op.drop_index(op.f('ix_energy_imported_timestamp'), table_name='energy_imported')
    op.drop_table('energy_imported')
    op.drop_index(op.f('ix_energy_exported_timestamp'), table_name='energy_exported')
    op.drop_table('energy_exported')
    op.drop_table('tariffs')
    op.drop_table('meters')
    op.drop_table('sites')
    op.drop_table('users')
    # ### end Alembic commands ###
