"""baseline schema

Revision ID: 6defe7ba9eda
Revises:
Create Date: 2026-09-21 20:53:17.320537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6defe7ba9eda"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summary_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summary_event")),
    )
    op.create_index(
        op.f("ix_summary_event_event_type"),
        "summary_event",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_summary_event_timestamp"), "summary_event", ["timestamp"], unique=False
    )
    op.create_table(
        "system_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("db_latency_ms", sa.Integer(), nullable=False),
        sa.Column("redis_latency_ms", sa.Integer(), nullable=False),
        sa.Column("row_counts", sa.JSON(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("mem_percent", sa.Float(), nullable=True),
        sa.Column("uptime_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_metrics")),
    )
    op.create_index(
        op.f("ix_system_metrics_timestamp"),
        "system_metrics",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sites_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
    )
    op.create_table(
        "meters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("serial_number", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_meters_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meters")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_meters_serial_number")),
    )
    op.create_table(
        "summary_kpi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("imported_kwh", sa.Float(), nullable=False),
        sa.Column("exported_kwh", sa.Float(), nullable=False),
        sa.Column("avg_max_power", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_summary_kpi_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summary_kpi")),
        sa.UniqueConstraint("site_id", "date", name="uq_summary_kpi_site_id_date"),
    )
    op.create_index(op.f("ix_summary_kpi_date"), "summary_kpi", ["date"], unique=False)
    op.create_index(
        op.f("ix_summary_kpi_site_id"), "summary_kpi", ["site_id"], unique=False
    )
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("price_per_kwh", sa.Float(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_tariffs_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_table(
        "energy_exported",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("measure_value", sa.Float(), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=True),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"], ["meters.id"], name=op.f("fk_energy_exported_meter_id_meters")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_exported")),
    )
    op.create_index(
        op.f("ix_energy_exported_timestamp"),
        "energy_exported",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "energy_imported",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("measure_value", sa.Float(), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=True),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"], ["meters.id"], name=op.f("fk_energy_imported_meter_id_meters")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_imported")),
    )
    op.create_index(
        op.f("ix_energy_imported_timestamp"),
        "energy_imported",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "energy_reactive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("imported_kvarh", sa.Float(), nullable=False),
        sa.Column("exported_kvarh", sa.Float(), nullable=False),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"], ["meters.id"], name=op.f("fk_energy_reactive_meter_id_meters")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_energy_reactive")),
    )
    op.create_index(
        op.f("ix_energy_reactive_timestamp"),
        "energy_reactive",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "max_power",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("measure_value", sa.Float(), nullable=False),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"], ["meters.id"], name=op.f("fk_max_power_meter_id_meters")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_max_power")),
    )
    op.create_index(
        op.f("ix_max_power_timestamp"), "max_power", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_max_power_timestamp"), table_name="max_power")
    op.drop_table("max_power")
    op.drop_index(op.f("ix_energy_reactive_timestamp"), table_name="energy_reactive")
    op.drop_table("energy_reactive")
    op.drop_index(op.f("ix_energy_imported_timestamp"), table_name="energy_imported")
    op.drop_table("energy_imported")
    op.drop_index(op.f("ix_energy_exported_timestamp"), table_name="energy_exported")
    op.drop_table("energy_exported")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_summary_kpi_site_id"), table_name="summary_kpi")
    op.drop_index(op.f("ix_summary_kpi_date"), table_name="summary_kpi")
    op.drop_table("summary_kpi")
    op.drop_table("meters")
    op.drop_table("sites")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_metrics_timestamp"), table_name="system_metrics")
    op.drop_table("system_metrics")
    op.drop_index(op.f("ix_summary_event_timestamp"), table_name="summary_event")
    op.drop_index(op.f("ix_summary_event_event_type"), table_name="summary_event")
    op.drop_table("summary_event")
    # ### end Alembic commands ###
