apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartenergy
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
  - certificate.yaml
  - middleware.yaml
images:
  - name: ghcr.io/etclank/smartenergy-api
    newName: ghcr.io/etclank/smartenergy-api
    digest: sha256:b9ed2c1be78d707f234df14e08679204a5249def787d0b8e26f398cce41e415f
