apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartenergy
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
  - certificate.yaml
  - middleware.yaml
images:
  - name: ghcr.io/etclank/smartenergy-api
    newName: ghcr.io/etclank/smartenergy-api
    digest: sha256:0d13398c342931d23d726b4db1903508272e45fefc27687f9cfe311798a4e363
