apiVersion: v1
kind: Service
metadata:
  name: smartenergy-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smartenergy-api
  ports:
    - name: http
      port: 8000
      targetPort: http
